### ISSUE TITLE
Is there an option to change the size of generated QR code?

### ISSUE THREAD

**Issue by fnxnet** [TorreyBetts/Alfred-QRCode#2]

**Comment by TorreyBetts** [comment]
Currently there is not a configurable way to change it. However, you can edit the line of code below to shrink the output or use the Preview app the barcode opens in to adjust the size from the tools menu.

`set aTransform to current application's CGAffineTransform's CGAffineTransformMakeScale(100.0, 100.0)`

The barcode on my system creates at 2300x2300. By lowering the percentage there, you can create a smaller QR code. Be sure to keep the numbers the same for the scale so it remains square.

Certainly this is something which would make a good addition to the workflow.

**Comment by fnxnet** [comment]
That's what I was trying first and for some reason MacOS Preview App opens it full screen anyway. Now I see when I set it at  10.0 all works fine. Thank you.
