### ISSUE TITLE
Output as SVG?

### ISSUE THREAD

**Issue by nk9** [TorreyBetts/Alfred-QRCode#4]
First off, thanks very much for the tool! It's great to have something which fits into my workflow so seamlessly so I can avoid visiting scammy QR Code generator sites. 😄 

I have managed to open the PDF created by this script and convert it to an SVG. But I'm wondering, since I will always want SVGs: is it possible for the API you're using to create SVGs natively? I guess this is a feature request, but I'm not familiar with this API to know if it's possible.

**Comment by TorreyBetts** [comment]
Unfortunately, CoreImage doesn't have SVG capabilities. If you're using the shortcut that opens the QR code in the Preview app, you can save in these formats:
<img width="432" alt="image" src="https://github.com/TorreyBetts/Alfred-QRCode/assets/5093679/9706ca29-adf4-48d9-8b9e-8994ac423d63">
